version: '2'

services:
  boilerplate-api-dev:
    build:
      context: .
    image: node:12.7.0
    environment:
      NODE_ENV: DEV
      DB_TYPE: postgres
      DB_HOST: boilerplate-db-dev
      DB_PORT: 5432
      DB_PASSWORD: boilerplate
      DB_USER: boilerplate
      DB_NAME: boilerplate-dev
      PASSWORD_SALT: 10
      JWT_ACCESS_SECRET: wfd32sdcs
      JWT_ACCESS_EXPIRY: 60s
      JWT_REFRESH_SECRET: dfhrfgdf
      JWT_REFRESH_EXPIRY: 10m
    volumes:
      - "./:/nest-js-boilerplate/"
    ports:
      - "3000:3000"
    links:
      - "boilerplate-db-dev"

  boilerplate-db-dev:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_USER=boilerplate
      - POSTGRES_DB=boilerplate-dev
    ports:
      - "5432:5432"
